# Generated by Django 6.0 on 2025-12-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='This is the default description'),
        ),
    ]
